### PR TITLE
Add Berlin peer lab @ SoundCloud

### PR DESCRIPTION
**Pull request by meghaphone**
🚀 🇩🇪

### CODE REVIEW

**Comment by ashfurrow** [comment]
:tada: :100:

**Comment by BasThomas** [comment]
The mail url (accidentally?) works being comma separated - at least in Mail.app. The two Twitter names don't, though...

**Comment by orta** [comment]
Good point, the site'll need to handle that being an array ( and add `[` `]` around the names. Should be. pretty simple fix

**Comment by meghaphone** [comment]
@orta want me to help fix it?? Let me know :) Can find a spare moment later today

**Pull request merged**
